name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  guard-ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install build
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check code formatting with isort
        run: |
          isort --profile=black --check-only guard/ tests/

      - name: Check code formatting with black
        run: |
          black --check guard/ tests/

      - name: Check linting with pylint
        run: |
          pylint guard/

      - name: Run tests with unittest
        run: |
          python -m unittest discover tests

      - name: Build the project
        run: |
          python -m build
